version: "3"
services:
 postgres:
   build: postgres
   expose:
    - 5432
 keycloak:
   build: keycloak
   expose:
    - 8080
 backend:
   volumes:
      - ./postgres/provision:/pg-certs
   links:
      - keycloak:auth.lumen.localhost
   expose:
      - 3000
   environment:
     - HOST_UID
     - HOST_GID
   depends_on:
     - postgres
     - keycloak
 client:
   environment:
     - HOST_UID
     - HOST_GID
 redis:
   image: redis:3.2.9
 windshaft:
   environment:
     - PGSSLROOTCERT=/pg-certs/server.crt
     - LUMEN_ENCRYPTION_KEY=supersecret
   volumes:
      - ./postgres/provision:/pg-certs
